ILogger has no `Info`, used `LogInformation` instead;
error CS0122: InteropErrorExtensions.Info(Interop.Error) is inaccessible due to its protection level